version: "3.9"
services:
  dotnet-api:
    build:
      context: ./UrlShortnerBackend
    ports:
      - "8080:8080"
    volumes:
      - ../pocket-url.db:/app/Data/pocket-url.db:rw
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=/app/Data/pocket-url.db;
  angular-app:
    build:
      context: ./
    ports:
      - "4200:80"
    depends_on:
      - dotnet-api

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"   # Exposes on VPS public port 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - dotnet-api
      - angular-app
