version: "3.9"
services:
  dotnet-api:
    build:
      context: ./UrlShortnerBackend
    ports:
      - "8080:8080"
    volumes:
      - ./sqlite/pocket-url.db:/app/Data/pocket-url.db:rw
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=/app/Data/pocket-url.db;

  angular-app:
    build:
      context: ./
    depends_on:
      - dotnet-api
    ports:
      - "8081:80"
    expose:
      - 80
